.TH IR\-KEYTABLE "1" "October 2010" "v4l-utils" "User Commands"
.SH NAME
ir-keytable \- Get or set IR keycode/scancode tables. 
.SH SYNOPSIS
.B ir\-keytable
[\fIoptions\fR] --device [\fI/dev/input/event* device\fR]
.br
.B ir-keytable
[\fIoptions\fR] --sysdev [\fIir class (f. ex. rc0)\fR]
.br
.B ir-keytable
[\fIoptions\fR] [\fIfor using the rc0 sysdev\fR]
.SH DESCRIPTION
Allows get/set IR keycode/scancode tables. 
.br You need to have read permissions on /dev/input for the program to work.
.SS "On the options below, the arguments are:"
.IP \fIDEV\fR
the /dev/input/event* device to control
.IP \fISYSDEV\fR
the ir class as found at /sys/class/rc
.IP \fITABLE\fR
a file wit a set of scancode=keycode value pairs
.IP \fISCANKEY\fR
a set of scancode1=keycode1,scancode2=keycode2,... value pairs
.IP \fIPROTOCOL\fR
protocol name (nec, rc\-5, rc\-6, other) to be enabled
.IP \fICFGFILE\fR
configuration file that associates a driver/table name with a keymap file
.PP
Options can be combined together.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-auto\-load\fR=\fICFGFILE\fR
Auto\-load a table, based on a configuration file.
Only works with sysdev.
.TP
\fB\-c\fR, \fB\-\-clear\fR
clears the old table
.TP
\fB\-d\fR, \fB\-\-device\fR=\fIDEV\fR
ir device to control
.TP
\fB\-k\fR, \fB\-\-set\-key\fR=\fISCANKEY\fR
Change scan/key pairs
.TP
\fB\-p\fR, \fB\-\-protocol\fR=\fIPROTOCOL\fR
Protocol to enable (the other ones will be
disabled). To enable more than one, use the option
more than one time
.TP
\fB\-r\fR, \fB\-\-read\fR
reads the current scancode/keycode table
.TP
\fB\-s\fR, \fB\-\-sysdev\fR=\fISYSDEV\fR
ir class device to control
.TP
\fB\-v\fR, \fB\-\-verbose\fR
enables debug messages
.TP
\fB\-w\fR, \fB\-\-write\fR=\fITABLE\fR
write (adds) the scancodes to the device
scancode/keycode table from an specified file
.TP
\fB\-?\fR, \fB\-\-help\fR
Give this help list
.TP
\fB\-\-usage\fR
Give a short usage message
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version
.PP
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SH BUGS
Report bugs to Mauro Carvalho Chehab <mchehab@redhat.com>.
